CREATE DATABASE VOCAB_UP

DROP DATABASE VOCAB_UP

CREATE TABLE USERS
(
	ID INT  PRIMARY KEY NOT NULL,
	USERNAME VARCHAR(50),
	PASS VARCHAR(100)
)

CREATE TABLE USER_INFO
(
	ID_USER INT PRIMARY KEY NOT NULL,
	EMAIL VARCHAR(30),
	NGSINH VARCHAR(30),
	BEGINDATE SMALLDATETIME,
	NAME NVARCHAR(30),
	TOTALWORD INT,
	HIGHEST_WORDS_COUNT INT,
	RECENT_WORDS_COUNT INT,
	GIOITINH NVARCHAR(10),
	CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID)
)
update USER_INFO set NGSINH = '111',NAME = 'thienphuoc',GIOITINH = 'nam' where ID_USER = 1
select * from USERS
select NGSINH,NAME,GIOITINH,EMAIL from USER_INFO where ID_USER = 1
select  from USERS, USER_INFO where USERS.ID = USER_INFO.ID_USER
update USER_INFO set GIOITINH = 'nam' where ID_USER = 1;
CREATE TABLE FLASHCARD 
(
	ID INT PRIMARY KEY NOT NULL,
	ENG VARCHAR(30),
	VIE NVARCHAR(30),
	PRONUNCIATION NVARCHAR(50),
	FIELD VARCHAR(20)
)

select * from FLASHCARD
select top 10 * from FLASHCARD fl_m where not exists(select fl.ID from FLASHCARD fl, USER_FLASHCARD u_fl where u_fl.ID_CARD = fl.ID and fl.ID = fl_m.ID and u_fl.ID_USER = 1 and u_fl.ID_COLLECTION = 0)
							and fl_m.FIELD = 'Animals'
order by NEWID()

CREATE TABLE USER_FLASHCARD
(
	ID_USER INT NOT NULL,
	ID_CARD INT NOT NULL,
	ID_COLLECTION INT NOT NULL,
	COLLECTION_NAME VARCHAR(100),
	CONSTRAINT PK_USER_FLASHCARD PRIMARY KEY (ID_USER, ID_CARD, ID_COLLECTION),
	CONSTRAINT FK_UF_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
	CONSTRAINT FK_UF_CARD FOREIGN KEY (ID_CARD) REFERENCES FLASHCARD (ID)
)

alter table USER_FLASHCARD
	alter column COLLECTION_NAME nvarchar(100)

select ID_COLLECTION, COLLECTION_NAME from USER_FLASHCARD where  ID_USER = 
delete from USER_FLASHCARD
select * from USER_FLASHCARD
insert into USER_FLASHCARD
values
(1,1,0,'HOCED'), -- bat buoc co nha dau buoi
(1,1,1,N'Đầu buồi'),
(1,1,2,N'Rẻ rách')

select  ID_COLLECTION, COLLECTION_NAME from USER_FLASHCARD where ID_USER = 1
select * from FLASHCARD
delete from FLASHCARD
INSERT INTO FLASHCARD
	(ID, ENG, VIE, PRONUNCIATION, FIELD)
VALUES
	(0,'Cover','','',''),
	(1, 'elephant', N'voi', N'/ˈelɪfənt/', 'Animals'),
	(2, 'fox', N'cáo', N'/fɑːks/', 'Animals'),
	(3, 'porcupine', N'con nhím',  N'/ˈpɔːrkjupaɪn/', 'Animals'),
	(4, 'giraffe', N'hươu cao cổ',   N'/dʒɪˈrɑːf/', 'Animals'),
	(5, 'hippopotamus', N'con hà mã', N'/ˌhɪpəˈpɑːtəməs/', 'Animals'),
	(6, 'jaguar', N'con báo đốm',   N'/ˈdʒæɡjuər/', 'Animals'),
	(7, 'dog', N'chó',  N'/dɒɡ/', 'Animals'),
	(8, 'raccoon', N'con gấu mèo',  N'/rækˈuːn/', 'Animals'),
	(9, 'bear', N'con gấu', N'/beər/', 'Animals'),
	(10, 'bird', N'con chim',  N'/bɜːd/', 'Animals'),
	(11, 'cat', N'con mèo', N'/kæt/', 'Animals'),
	(12, 'cow', N'con bò',  N'/kaʊ/', 'Animals'),
	(13, 'donkey', N'con lừa', N'/ˈdɒŋ.ki/', 'Animals'),
	(14, 'fish', N'con cá', N'/fɪʃ/', 'Animals'),
	(15, 'goat', N'con dê',  N'/ɡəʊt/', 'Animals'),
	(16, 'lion', N'con sư tử', N'/ˈlaɪ.ən/', 'Animals'),
	(17, 'money', N'con khỉ',  N'/ˈmʌŋ.ki/', 'Animals'),
	(18, 'pig', N'con heo',  N'/pɪɡ/', 'Animals'),
	(19, 'rabbit', N'con thỏ',  N'/ˈræb.ɪt/', 'Animals'),
	(20, 'sheep', N'con cừu',  N'/ʃiːp/', 'Animals'),
	(21, 'alligator', N'cá sấu', N'/ˈælɪɡeɪtər/', 'Animals'),
	(22, 'bat', N'dơi', N'/bæt/', 'Animals'),
	(23, 'deer', N'con hươu',  N'/dɪər/ ', 'Animals'),
	(24, 'wolf', N'chó sói',   N'/wʊlf/', 'Animals'),
	(25, 'beaver', N'con hải ly', N'/ˈbiːvər/', 'Animals'),
	(26, 'chipmunk', N'sóc chuột',   N'/ˈtʃɪpmʌŋk/', 'Animals'),
	(27, 'dolphin', N'cá heo',  N'/ˈdɒlfɪn/', 'Animals'),
	(28, 'shark', N'con cá mập',  N'/ʃɑːk/', 'Animals'),
	(29, 'whale', N'con cá voi', N'/weɪl/', 'Animals'),
	(30, 'bird', N'con chim',  N'/bɜːd/', 'Animals'),
	(31, 'eel', N'con lươn', N'/iːl/', 'Animals'),
	(32, 'swordfish', N'cá kiếm',  N'/ˈsɔːdfɪʃ/', 'Animals'),
	(33, 'walrus', N'hải mã', N'/ˈwɔːlrəs/', 'Animals'),
	(34, 'penguin', N'chim cánh cụt', N'/ˈpeŋɡwɪn/', 'Animals'),
	(35, 'turtle', N'con rùa',  N'/ˈtɜːtl/', 'Animals'),
	(36, 'bee', N'con ong', N'/biː/', 'Animals'),
	(37, 'camel', N'con lạc đà',  N'/ˈkæməl/', 'Animals'),
	(38, 'cobra', N'con rắn hổ mang',  N'/ˈkəʊ.brə/', 'Animals'),
	(39, 'scorpion', N'con bọ cạp',  N'scorpion', 'Animals'),
	(40, '﻿hedgehog', N'con nhím',  N'/ˈhedʒ.hɒɡ/', 'Animals'),
	(41, 'moose', N'nai sừng tấm Bắc Mỹ', N'/muːs/ ', 'Animals'),
	(42, 'zebra', N'ngựa vằn', N'/ˈzebrə/', 'Animals'),
	(43, 'bison', N'bò rừng bizon',  N'/ˈbaɪsn/', 'Animals'),
	(44, 'llama', N'lạc đà không bướu',   N'/ˈlɑːmə/', 'Animals'),
	(45, '﻿jellyfish', N'con sứa', N'/ˈdʒel.i.fɪʃ/', 'Animals'),
	(46, 'octopus', N'con bạch tuộc',   N'/ˈɑːktəpəs/', 'Animals'),
	(47, 'pufferfish', N'cá nóc',  N'/ˈpʌfərfɪʃ/', 'Animals'),
	(48, 'squid', N'con mực',  N'/skwɪd/', 'Animals'),
	(49, 'starfish', N'sao biển', N'/ˈstɑːrfɪʃ/', 'Animals'),
	(50, 'stingray', N'cá đuối',  N'/ˈstɪŋreɪ/', 'Animals'),
	(51, '﻿squirrel', N'con sóc', N'/ˈskwɪr.əl/', 'Animals'),
	(52, 'kangaroo', N'con chuột túi', N'/koʊˈɑːlə/', 'Animals'),
	(53, 'koala', N'con gấu koala',  N'/ˈpɔːrkjupaɪn/', 'Animals'),
	(54, 'panda', N'con gấu trúc',   N'/ˈpændə/', 'Animals'),
	(55, 'platypus', N'thú mỏ vịt', N'/ˈplætɪpəs/', 'Animals'),
	(56, 'hyena', N'con linh cẩu',   N'/haɪˈiː.nə/', 'Animals'),
	(57, 'gnu', N'linh dương đầu bò',  N'/nuː/', 'Animals'),
	(58, 'baboon', N'khỉ đầu chó',  N'/bəˈbuːn/', 'Animals'),
	(59, 'owl', N'cú mèo', N'/aʊl/', 'Animals'),
	(60, 'eagle', N'con chim đại bàng',  N'/ˈiː.gl/', 'Animals'),
	(61, 'woodpecker', N'chim gõ kiến', N'/ˈwʊdˌpek.əʳ/', 'Animals'),
	(62, 'peacock', N'con công', N'/ˈpiː.kɒk/', 'Animals'),
	(63, 'sparrow', N'con chim sẻ',  N'/ˈspær.əʊ/', 'Animals'),
	(64, 'heron', N'diệc',   N'/ˈher.ən/', 'Animals'),
	(65, 'swan', N'thiên nga', N'/swɒn/', 'Animals'),
	(66, 'falcon', N'con chim ưng', N'/ˈfɒl.kən/', 'Animals'),
	(67, 'nest', N'cái tổ',  N'/nest/', 'Animals'),
	(68, 'ostrich', N'đà điểu',  N'/ˈɒs.trɪtʃ/', 'Animals'),
	(69, 'feather', N'lông vũ', N'/ˈfeð.əʳ/', 'Animals'),
	(70, 'talon', N'móng vuốt',  N'/ˈtæl.ən/', 'Animals'),
	(71, 'seagull', N'mòng biển', N'/ˈsiː.gʌl/', 'Animals'),
	(72, 'octopus', N'bạch tuộc', N'/ˈɒk.tə.pəs/', 'Animals'),
	(73, 'lobster', N'tôm hùm',  N'/ˈlɒb.stəʳ/', 'Animals'),
	(74, 'shellfish', N'ốc',   N'/ˈʃel.fɪʃ/', 'Animals'),
	(75, 'killer whale', N'cá voi sát thủ', N'/ˈkɪl.əʳ weɪl/', 'Animals'),
	(76, 'squid', N'mực ống',   N'/skwɪd/', 'Animals'),
	(77, 'coral', N'san hô',  N'/ˈkɒr.əl/', 'Animals'),
	(78, 'raccoon', N'con gấu mèo',  N'/rækˈuːn/', 'Animals'),
	(79, 'boar', N'lợn hoang', N'/bɔːʳ/', 'Animals'),
	(80, 'bird', N'con chim',  N'/bɜːd/', 'Animals'),
	(81, 'lynx', N'mèo rừng Mĩ', N'/lɪŋks/', 'Animals'),
	(82, 'skunk', N'chồn hôi', N'/skʌŋk/', 'Animals'),
	(83, 'caterpillar', N'sâu bướm',  N'/ˈkæt.ə.pɪl.əʳ/', 'Animals'),
	(84, 'praying mantis', N'bọ ngựa', N'/preiɳˈmæn.tɪs/', 'Animals'),
	(85, 'honeycomb', N'sáp ong', N'/ˈhʌn.i.kəʊm/', 'Animals'),
	(86, 'tarantula', N'loại nhện lớn',   N'/təˈræn.tjʊ.lə/', 'Animals'),
	(87, 'parasites', N'kí sinh trùng',  N'/’pærəsaɪt/', 'Animals'),
	(88, 'ladybug', N'bọ rùa',  N'/ˈleɪ.di.bɜːd/', 'Animals'),
	(89, 'mosquito', N'con muỗi', N'/məˈskiː.təʊ/', 'Animals'),
	(90, 'Cockroach', N'con gián',  N'/ˈkɒk.rəʊtʃ/', 'Animals'),
	(91, 'grasshopper', N'châu chấu', N'/ˈgrɑːsˌhɒp.əʳ/', 'Animals'),
	(92, 'honeycomb', N'sáp ong', N'/ˈhʌn.i.kəʊm/', 'Animals'),
	(93, 'toad', N'con cóc',  N'/təʊd/', 'Animals'),
	(94, 'dragon', N'con rồng',   N'/ˈdræg.ən/', 'Animals'),
	(95, 'turkey', N'con gà tây', N'/tɜrki/', 'Animals'),
	(96, 'minnow', N'cá tuế',   N'/’minou/', 'Animals'),
	(97, 'orca', N'cá kình',  N'/’ɔ:kə/', 'Animals'),
	(98, 'cricket', N'Con dế',  N'/’krɪkɪt/', 'Animals'),
	(99, 'locust', N'cào cào', N'/’loukəst/', 'Animals'),
	(100, 'cicada', N'Ve sầu',  N'/si’kɑ:də/', 'Animals')

INSERT INTO FLASHCARD
	(ID, ENG, VIE, PRONUNCIATION, FIELD)
VALUES
	(101, 'hardware', N'phần cứng', N'/ˈhɑːdweə(r)/', 'Technology'),
	(102, 'software', N'phần mềm', N'/ˈsɒftweə(r)/', 'Technology'),
	(103, 'main memory system', N'hệ thống bộ nhớ chính',  N'/meɪnˈmeməriˈsɪstəm/', 'Technology'),
	(104, 'registers', N'các thanh ghi',   N'/ˈredʒɪstə(r)z/', 'Technology'),
	(105, 'input', N'bộ vào', N'/ˈɪnpʊt/', 'Technology'),
	(106, 'output', N'bộ ra',   N'/ˈaʊtpʊt/', 'Technology'),
	(107, 'cache memory', N'bộ nhớ Cache',  N'/kæʃ ˈmeməri/', 'Technology'),
	(108, 'instruction', N'hướng dẫn',  N'/ɪnˈstrʌkʃn/', 'Technology'),
	(109, 'program', N'chương trình', N'/ˈprəʊɡræm/', 'Technology'),
	(110, 'secondary memory', N'bộ nhớ phụ',  N'/ˈsekəndriˈmeməri/', 'Technology'),
	(111, 'floppy disk', N'đĩa mềm', N'/ˈflɒpi dɪsk/', 'Technology'),
	(112, 'hard disk', N'đĩa cứng',  N'/hɑːd dɪsk/', 'Technology'),
	(113, 'compact disk', N'đĩa quang', N'/kəmˈpækt dɪsk/', 'Technology'),
	(114, 'memory stick', N'thẻ nhớ', N'/ˈmeməri stɪk/', 'Technology'),
	(115, 'function keypad', N'nhóm phím chức năng',  N'/ˈfʌŋkʃn ˈkiːpæd/', 'Technology'),
	(116, 'numeric keypad', N'nhóm phím số', N'/njuːˈmerɪk ˈkiːpæd/', 'Technology'),
	(117, 'text', N'văn bản',  N'/tekst/', 'Technology'),
	(118, 'graphics', N'đồ họa',  N'/ˈɡræfɪks/', 'Technology'),
	(119, 'microprocessor', N'bộ vi xử lý',  N'/ˌmaɪ.krəʊˈprəʊ.ses.ər/', 'Technology'),
	(120, 'port', N'cổng',  N'/pɔːt/', 'Technology'),
	(121, 'software developer', N'nhà phát triển phần mềm', N'/ˈsɒftweə(r) dɪˈveləpə(r)/', 'Technology'),
	(122, 'computer programmer', N'nhà lập trình máy tính', N'/kəmˈpjuːtə(r) ˈprəʊɡræmə(r)/', 'Technology'),
	(123, 'operating system ', N'hệ điều hành',  N'/ˈɒpəreɪtɪŋ ˈsɪstəm/ ', 'Technology'),
	(124, 'information', N'thông tin',   N'/ˌɪnfəˈmeɪʃn/', 'Technology'),
	(125, 'data', N'dữ liệu', N'/ˈdeɪtə/', 'Technology'),
	(126, 'programming language', N'ngôn ngữ lập trình',   N'/ˈprəʊɡræmɪŋ ˈlæŋɡwɪdʒ/', 'Technology'),
	(127, 'convert', N'chuyển đổi',  N'/kənˈvɜːt/', 'Technology'),
	(128, 'browser', N'trình duyệt',  N'/ˈbraʊzə(r)/', 'Technology'),
	(129, 'application', N'ứng dụng', N'/ˌæplɪˈkeɪʃn/', 'Technology'),
	(130, 'storage', N'lưu trữ',  N'/ˈstɔːrɪdʒ/', 'Technology'),
	(131, 'available', N'có sẵn', N'/əˈveɪləbl/', 'Technology'),
	(132, 'version', N'phiên bản',  N'/ˈvɜːʃn/', 'Technology'),
	(133, 'official', N'chính thức', N'/əˈfɪʃl/', 'Technology'),
	(134, 'beta', N'thử nghiệm', N'/ˈbiːtə/', 'Technology'),
	(135, 'compatible', N'tương thích',  N'/kəmˈpætəbl/', 'Technology'),
	(136, 'customer', N'khách hàng', N'/ˈkʌstəmə(r)/', 'Technology'),
	(137, 'develop', N'phát triển',  N'/dɪˈveləp/', 'Technology'),
	(138, 'interrupt', N'cản trở, gián đoạn',  N'/ˌɪntəˈrʌpt/', 'Technology'),
	(139, 'install ', N'cài đặt',  N'/ɪnˈstɔːl/', 'Technology'),
	(140, '﻿latest', N'mới nhất',  N'/ˈleɪtɪst/', 'Technology'),
	(141, 'maintain', N'duy trì', N'/meɪnˈteɪn/ ', 'Technology'),
	(142, 'matrix', N'ma trận', N'/ˈmeɪtrɪks/', 'Technology'),
	(143, 'respond', N'phản hồi',  N'/rɪˈspɒnd/', 'Technology'),
	(144, 'signal', N'tín hiệu',   N'/ˈsɪɡnəl/', 'Technology'),
	(145, '﻿transmit', N'truyền', N'/trænzˈmɪt/', 'Technology'),
	(146, 'addition', N'Phép cộng',   N'/əˈdɪʃn/', 'Technology'),
	(147, 'subtraction', N'Phép trừ',  N'/səbˈtrækʃn/', 'Technology'),
	(148, 'multiplication', N'Phép nhân',  N'/ˌmʌltɪplɪˈkeɪʃn/', 'Technology'),
	(149, 'division', N'Phép chia', N'/dɪˈvɪʒn/', 'Technology'),
	(150, 'device', N'thiết bị',  N'/dɪˈvaɪs/', 'Technology'),
	(151, '﻿function', N'chức năng', N'/ˈfʌŋkʃn/', 'Technology'),
	(152, 'personalize', N'cá nhân hóa', N'/ˈpɜːsənəlaɪz/', 'Technology'),
	(153, 'setting', N'cài đặt',  N'/ˈsetɪŋ/', 'Technology'),
	(154, 'feature', N'thuộc tính',   N'/ˈfiːtʃə(r)/', 'Technology'),
	(155, 'fundamental', N'cơ bản', N'/ˌfʌndəˈmentl/', 'Technology'),
	(156, 'internal', N'bên trong',   N'/ɪnˈtɜːnl/', 'Technology'),
	(157, 'intricate', N'phức tạp',  N'/ˈɪntrɪkət/', 'Technology'),
	(158, 'font', N'phông',  N'/fɒnt/', 'Technology'),
	(159, 'bug', N'lỗi', N'/bʌɡ/', 'Technology'),
	(160, 'crash', N'hỏng chương trình',  N'/kræʃ/', 'Technology'),
	(161, 'security', N'bảo mật', N'/sɪˈkjʊərəti/', 'Technology'),
	(162, 'database', N'cơ sở dữ liệu', N'/ˈdeɪtəbeɪs/', 'Technology'),
	(163, 'algorithm', N'thuật toán',  N'/ˈælɡərɪðəm/', 'Technology'),
	(164, 'source Code', N'mã nguồn',   N'/sɔːs kəʊd/', 'Technology'),
	(165, 'pulse', N'xung', N'/pʌls/', 'Technology'),
	(166, 'modify', N'phân loại',   N'/ˈmɒdɪfaɪ/', 'Technology'),
	(167, 'gateway', N'cổng kết nối Internet',  N'/ˈɡeɪtweɪ/', 'Technology'),
	(168, 'protocol', N'giao thức',  N'/ˈprəʊtəkɒl/', 'Technology'),
	(169, 'configuration', N'cấu hình', N'/kənˌfɪɡəˈreɪʃn/', 'Technology'),
	(170, 'adware', N'phần mềm quảng cáo',  N'/ˈædweə(r)/', 'Technology'),
	(171, 'buffer overflow', N'lỗi tràn bộ nhớ đệm', N'/ˈbʌfə(r) ˌəʊvəˈfləʊ/', 'Technology'),
	(172, 'debugging', N'gỡ lỗi', N'/ˌdiːˈbʌɡɪŋ/', 'Technology'),
	(173, 'machine language', N'ngôn ngữ máy',  N'/məˈʃiːn ˈlæŋɡwɪdʒ/', 'Technology'),
	(174, 'interpreter', N'trình thông dịch',   N'/ɪnˈtɜːprətə(r)/', 'Technology'),
	(175, 'firewall', N'tường lửa', N'/ˈfaɪəwɔːl/', 'Technology'),
	(176, 'cursor', N'con trỏ trong cơ sở dữ liệu',   N'/ˈkɜːsə(r)/', 'Technology'),
	(177, 'backup', N'sao lưu',  N'/ˈbækʌp/', 'Technology'),
	(178, 'format', N'định dạng',  N'/ˈfɔːmæt/', 'Technology'),
	(179, 'unplugged', N'chưa được kết nối', N'/ˌʌnˈplʌɡd/', 'Technology'),
	(180, 'spyware', N'phần mềm gián điệp',  N'/ˈspaɪweə(r)/', 'Technology'),
	(181, 'administration', N'quyền quản trị', N'/ədˌmɪnɪˈstreɪʃn/', 'Technology'),
	(182, 'domain', N'tên miền', N'/dəˈmeɪn/', 'Technology'),
	(183, 'malware', N'phần mềm độc hại',  N'/ˈmælweə(r)/', 'Technology'),
	(184, 'cloud computing', N'điện toán đám mây',   N'/klaʊd kəmˈpjuːtɪŋ/', 'Technology'),
	(185, 'antivirus software', N'phần mềm chống virus', N'/ˈæntivaɪrəs ˈsɒftweə(r)/', 'Technology'),
	(186, 'internet service provider', N'nhà cung cấp dịch vụ mạng',   N'/ˈɪntənet ˈsɜːvɪs prəˈvaɪdə(r)/', 'Technology'),
	(187, 'speech recognition', N'nhận dạng tiếng nói',  N'/spiːtʃ ˌrekəɡˈnɪʃn/', 'Technology'),
	(188, 'quantum computing', N'máy tính lượng tử',  N'/ˈkwɒntəm kəmˈpjuːtɪŋ/', 'Technology'),
	(189, 'command', N'mệnh lệnh', N'/kəˈmɑːnd/', 'Technology'),
	(190, 'prolog', N'lập trình theo lôgic',  N'/ˈprəʊlɒɡ/', 'Technology'),
	(191, 'concurrency control', N'kiểm soát truy cập đồng thời', N'/kənˈkʌr(ə)nsɪ kənˈtrəʊl/', 'Technology'),
	(192, 'optimize', N'tối ưu hóa', N'/ˈɒptɪmaɪz/', 'Technology'),
	(193, 'analysis', N'phân tích',  N'/əˈnæləsɪs/', 'Technology'),
	(194, 'encryption', N'mã hóa dữ liệu',   N'/ɪnˈkrɪpʃn/', 'Technology'),
	(195, 'bus', N'mạng trục tuyến', N'/bʌs/', 'Technology'),
	(196, 'transistor', N'linh kiện bán dẫn',   N'/trænˈzɪstə(r)/', 'Technology'),
	(197, 'worm', N'sâu máy tính',  N'/wɜːm/', 'Technology'),
	(198, 'hyperlink', N'siêu liên kết',  N'/ˈhaɪpəlɪŋk/', 'Technology'),
	(199, 'single-tasking', N'đơn nhiệm', N'/ˈsɪŋɡl tɑːskɪŋ/', 'Technology'),
	(200, 'program execution', N'thực thi chương trình',  N'/ˈprəʊɡræm ˌeksɪˈkjuːʃn/', 'Technology')

INSERT INTO FLASHCARD
	(ID, ENG, VIE, PRONUNCIATION, FIELD)
VALUES
	(201, 'acccessories', N'phụ kiện', N'/ækˈsɛsəriz/', 'Clothing'),
	(202, 'belt', N'thắt lưng', N'/bɛlt/', 'Clothing'),
	(203, 'blouse', N'áo sơ mi (nữ)', N'/blaʊs/', 'Clothing'),
	(204, 'boot', N'ủng', N'/but/', 'Clothing'),
	(205, 'coat', N'áo khoác', N'/koʊt/', 'Clothing'),
	(206, 'dress', N'váy liền', N'/drɛs/', 'Clothing'),
	(207, 'fit', N'vừa vặn', N'/fɪt/', 'Clothing'),
	(208, 'glove', N'găng tay', N'/glʌv/', 'Clothing'),
	(209, 'glasses', N'mắt kính', N'/ˈglæsəz/', 'Clothing'),
	(210, 'handbag', N'túi xách', N'/ˈhændˌbæg/', 'Clothing'),
	(211, 'hat', N'mũ', N'/hæt/', 'Clothing'),
	(212, 'jacket', N'áo khoác', N'/ˈʤækət/', 'Clothing'),
	(213, 'jeans', N'quần jean', N'/ʤinz/', 'Clothing'),
	(214, 'pants', N'quần dài', N'/Pænts/', 'Clothing'),
	(215, 'pyjama', N'quần áo ngủ', N'/pəˈjäməz/', 'Clothing'),
	(216, 'sandal', N'dép xăng đan', N'/ˈsændəl/', 'Clothing'),
	(217, 'scarf', N'khăn quàng cổ', N'/skɑrf/', 'Clothing'),
	(218, 'shirt', N'áo sơ mi', N'/ʃɜrt/', 'Clothing'),
	(219, 'shoes', N'đôi giày', N'/ʃuz/', 'Clothing'),
	(220, 'short', N'quần sooc', N'/ʃɔrt/', 'Clothing'),
	(221, 'skirt', N'váy', N'/skɜrt/', 'Clothing'),
	(222, 'socks', N'tất', N'/sɑks/', 'Clothing'),
	(223, 'suit', N'bộ comple', N'/sut/', 'Clothing'),
	(224, 'sweater', N'áo len', N'/ˈswɛtər/', 'Clothing'),
	(225, 'swimsuit ', N'đồ bơi', N'/ˈswɪmˌsut/', 'Clothing'),
	(226, 'tie', N'cà vạt', N'/taɪ/', 'Clothing'),
	(227, 'trousers', N'quần dài', N'/ˈtraʊzərz/', 'Clothing'),
	(228, 'cap', N'mũ lưỡi trai', N'/kæp/', 'Clothing'),
	(229, 'cardigan', N'áo khoác len', N'/ˈkɑːdɪɡən/', 'Clothing'),
	(230, 'bathrobe', N'áo choàng tắm', N'/ˈbɑːθrəʊb/', 'Clothing'),
	(231, 'nightdress', N'đầm ngủ', N'/ˈnaɪtdres/', 'Clothing'),
	(232, 'watch', N'đồng hồ đeo tay', N'/wɑːtʃ/', 'Clothing'),
	(233, 'wallet', N'ví', N'/ˈwɑːlɪt/', 'Clothing'),
	(234, 'raincoat', N'áo mưa', N'/ˈreɪŋ.kəʊt/', 'Clothing'),
	(235, 'anorak', N'áo khoác chống nước có mũ', N'/ˈæn.ə.ræk/', 'Clothing'),
	(236, 'slipper', N'dép đi trong nhà', N'/ˈslɪp.ər/', 'Clothing'),
	(237, 'shoelace', N'dây giày', N'/ˈʃuː.leɪs/', 'Clothing'),
	(238, 'wellington', N'ủng cao su', N'/ˈwel.ɪŋ.tən/', 'Clothing'),
	(239, 'pullover', N'áo len chui đầu', N'/ˈpʊlˌəʊ.vər/', 'Clothing'),
	(240, 'coveralls', N'quần yếm', N'/ˈkʌv.ə.rɔːlz/', 'Clothing'),
	(241, 'bracelet', N'vòng tay', N'/ˈbreɪ.slət/', 'Clothing'),
	(242, 'necklace', N'vòng cổ', N'/ˈnek.ləs/', 'Clothing'),
	(243, 'comb', N'lược thẳng', N'/kəʊm/', 'Clothing'),
	(244, 'bra', N'áo lót nữ', N'/brɑː/', 'Clothing'),
	(245, 'knickers', N'quần lót nữ', N'/ˈnɪk.əz/', 'Clothing'),
	(246, 'underpants', N'quần lót nam', N'/ˈʌn.də.pænts/', 'Clothing'),
	(247, 'tights', N'quần tất', N'/taɪts/', 'Clothing'),
	(248, 'handkerchief', N'khăn tay', N'/ˈhæŋ.kə.tʃiːf/', 'Clothing'),
	(249, 'earmuffs', N'mũ len che tai', N'/ˈɪə.mʌfs/', 'Clothing'),
	(250, 'mitten', N'găng tay', N'/ˈmɪt.ən/', 'Clothing'),
	(251, 'silk', N'lụa', N'/sɪlk/', 'Clothing'),
	(252, 'cotton', N'bông', N'/ˈkɒt.ən/', 'Clothing'),
	(253, 'leather', N'da', N'/ˈleð.ər/', 'Clothing'),
	(254, 'khaki', N'vải ka-ki', N'/ˈkɑː.ki/', 'Clothing'),
	(255, 'linen', N'vải lanh', N'/ˈlɪn.ɪn/', 'Clothing'),
	(256, 'damask', N'lụa Đa-mát', N'/ˈdæm.əsk/', 'Clothing'),
	(257, 'feather', N'lông vũ', N'/ˈfeð.ər/', 'Clothing'),
	(258, 'synthetic', N'sợi tổng hợp', N'/sɪnˈθet.ɪk/', 'Clothing'),
	(259, 'wool', N'len', N'/wʊl/', 'Clothing'),
	(260, 'denim', N'vải bò', N'/ˈden.ɪm/', 'Clothing'),
	(261, 'collar', N'cổ áo', N'/ˈkɒl.ər/', 'Clothing'),
	(262, 'seam', N'đường may', N'/siːm/', 'Clothing'),
	(263, 'sleeve', N'tay áo', N'/sliːv/', 'Clothing'),
	(264, 'lappet', N'vạt áo', N'/ˈlapət/', 'Clothing'),
	(265, 'button', N'khuy áo', N'/ˈbʌt.ən/', 'Clothing'),
	(266, 'loafer', N'giày lười', N'/‘loufə/', 'Clothing'),
	(267, 'stilettos', N'giày gót nhọn', N'/stɪˈletoʊ/', 'Clothing'),
	(268, 'balaclava', N'mũ trùm', N'/ˌbæl.əˈklɑː.və/', 'Clothing'),
	(269, 'beret', N'mũ nồi', N'/bəˈreɪ/', 'Clothing'),
	(270, 'bowler', N'mũ quả dưa', N'/ˈbəʊlər/', 'Clothing'),
	(271, 'deerstalker', N'mũ thợ săn', N'/ˈdɪəˌstɔː.kər/', 'Clothing'),
	(272, 'fedora', N'mũ phớt', N'/fəˈdɔː.rə/', 'Clothing'),
	(273, 'helmet', N'mũ bảo hiểm', N'/ˈhelmɪt/', 'Clothing'),
	(274, 'hard hat', N'mũ bảo hộ', N'/ˈhɑːd hæt/', 'Clothing'),
	(275, 'snapback', N'mũ lưỡi trai phẳng', N'/snæp¸bæk/', 'Clothing'),
	(276, 'clog', N'guốc', N'/klɔg/', 'Clothing'),
	(277, 'sneaker', N'giày thể thao', N'/ˈsniːkə(r)/', 'Clothing'),
	(278, 'wedge boot', N'nêm giầy ủng', N'/uh bu:t/', 'Clothing'),
	(279, 'moccasin', N'giày Mocca', N'/’mɔkəsin/', 'Clothing'),
	(280, 'bucket hat ', N'mũ tai bèo', N'/ˈbʌkɪt hæt/', 'Clothing'),
	(281, 'blazer', N'áo khoác vest', N'/´bleizə/', 'Clothing'),
	(282, 't-shirt', N'áo phông', N'/ti:’∫ə:t/', 'Clothing'),
	(283, 'boxer shorts', N'quần đùi', N'/´bɔksə ʃɔ:t/', 'Clothing'),
	(284, 'kimono', N'áo ki-mô-nô', N'/kɪˈməʊ.nəʊ/', 'Clothing'),
	(285, 'tuxedo', N'tuxedo', N'/tʌkˈsiː.dəʊ/', 'Clothing'),
	(286, 'costume', N'trang phục', N'/ˈkɒs.tʃuːm/', 'Clothing'),
	(287, 'muumuu', N'váy dài (phụ nữ Hawaii)', N'/ˈmo͞omo͞o/', 'Clothing'),
	(288, 'pinafore', N'yếm dãi trẻ con', N'/ˈpɪn.ə.fɔːr/', 'Clothing'),
	(289, 'parka', N'áo khoác chống gió có mũ', N'/ˈpɑː.kə/', 'Clothing'),
	(290, 'peplum', N'váy ngắn', N'/ˈpep.ləm/', 'Clothing'),
	(291, 'stocking', N'tất da', N'/ˈstɒk.ɪŋ/', 'Clothing'),
	(292, 'tank top', N'áo ba lỗ', N'/ˈtæŋk ˌtɒp/', 'Clothing'),
	(293, 'gilet', N'áo gi lê', N'/ˈdʒɪl.eɪ/', 'Clothing'),
	(294, 'camisole', N'áo yếm', N'/ˈkæm.ɪ.səʊl/', 'Clothing'),
	(295, 'capri pants', N'quần lửng', N'/kəˈpriː ˌpænts/', 'Clothing'),
	(296, 'diaper', N'tã lót', N'/ˈdaɪ.pər/', 'Clothing'),
	(297, 'flip-flop', N'dép tông', N'/ˈflɪp.flɒp/', 'Clothing'),
	(298, 'headscarf', N'khăn trùm đầu', N'/ˈhed.skɑːf/', 'Clothing'),
	(299, 'high heels', N'cao gót', N'/ˌhaɪ ˈhiːlz/', 'Clothing'),
	(300, 'jodhpurs', N'quần đi ngựa', N'/ˈdʒɒd.pəz/', 'Clothing')
	
INSERT INTO FLASHCARD
	(ID, ENG, VIE, PRONUNCIATION, FIELD)
VALUES
	(301, 'fork', N'nĩa', N'/fɔːrk/', 'Food and Drinks'),
	(302, 'spoon', N'muỗng', N'/spuːn/', 'Food and Drinks'),
	(303, 'knife', N'dao',  N'/naɪf/', 'Food and Drinks'),
	(304, 'ladle', N'cái vá múc canh',   N'/ˈleɪdl/', 'Food and Drinks'),
	(305, 'bowl', N'tô', N'/boʊl/', 'Food and Drinks'),
	(306, 'plate', N'đĩa',   N'/pleɪt/', 'Food and Drinks'),
	(307, 'chopsticks', N'đũa',  N'/ˈtʃɑːpstɪkz/', 'Food and Drinks'),
	(308, 'teapot', N'ấm trà',  N'/ˈtiːpɑːt/', 'Food and Drinks'),
	(309, 'cup', N'cái tách uống trà', N'/kʌp/', 'Food and Drinks'),
	(310, 'glass', N'cái ly',  N'/ɡlæs/', 'Food and Drinks'),
	(311, 'straw', N'ống hút', N'/strɔː/', 'Food and Drinks'),
	(312, 'pitcher', N'bình nước',  N'/ˈpɪtʃər/', 'Food and Drinks'),
	(313, 'mug', N'cái ly nhỏ có quai', N'/mʌɡ/', 'Food and Drinks'),
	(314, 'napkin', N'khăn ăn', N'/ˈnæpkɪn/', 'Food and Drinks'),
	(315, 'table cloth', N'khăn trải bàn',  N'/ˈteɪbl klɔːθ /', 'Food and Drinks'),
	(316, 'tongs', N'cái kẹp gắp thức ăn', N'/tɑːŋz/', 'Food and Drinks'),
	(317, 'wheat', N'bột mì',  N'/wiːt/', 'Food and Drinks'),
	(318, 'cheese', N'phô mai',  N'/tʃiːz/', 'Food and Drinks'),
	(319, 'butter', N'bơ',  N'/ˈbʌtər/', 'Food and Drinks'),
	(320, 'dairy product', N'sản phẩm làm từ sữa',  N'/ˈderi ˈprɑːdʌkt /', 'Food and Drinks'),
	(321, 'nut', N'đậu phộng', N'/nʌt/', 'Food and Drinks'),
	(322, 'beans', N'đậu', N'/biːnz/', 'Food and Drinks'),
	(323, 'peas', N'đậu hạt tròn',  N'/piːz/', 'Food and Drinks'),
	(324, 'vegetable', N'rau',   N'/ˈvedʒtəbl/', 'Food and Drinks'),
	(325, 'salad', N'món trộn, gỏi', N'/ˈsæləd/', 'Food and Drinks'),
	(326, 'noodles', N'mì',   N'/ˈnuːdlz/', 'Food and Drinks'),
	(327, 'spaghetti', N'mì Ý',  N'/spəˈɡeti/', 'Food and Drinks'),
	(328, 'pasta', N'mì ống',  N'/ˈpɑːstə/', 'Food and Drinks'),
	(329, 'fried rice', N'cơm chiên', N'/fraɪd raɪs/', 'Food and Drinks'),
	(330, 'sauce', N'xốt',  N'/sɔːs/', 'Food and Drinks'),
	(331, 'soup', N'súp', N'/suːp/', 'Food and Drinks'),
	(332, 'sausage', N'xúc xích',  N'/ˈsɔːsɪdʒ/', 'Food and Drinks'),
	(333, 'hot pot', N'lẩu', N'/hɑːt pɑːt /', 'Food and Drinks'),
	(334, 'pork', N'thịt lợn', N'/pɔːrk/', 'Food and Drinks'),
	(335, 'beef', N'thịt bò',  N'/biːf/', 'Food and Drinks'),
	(336, 'chicken', N'thịt gà', N'/ˈtʃɪkɪn/', 'Food and Drinks'),
	(337, 'roasted food', N'đồ quay',  N'/roʊstɪd fuːd/', 'Food and Drinks'),
	(338, 'grilled food', N'đồ nướng',  N'/ ɡrɪl fuːd/', 'Food and Drinks'),
	(339, 'fried food', N'đồ chiên',  N'/fraɪd fuːd /', 'Food and Drinks'),
	(340, '﻿saute', N'đồ xào',  N'/soʊˈteɪ/', 'Food and Drinks'),
	(341, 'stew', N'đồ hầm', N'/stuː/', 'Food and Drinks'),
	(342, 'steam food', N'đồ hấp', N'/stiːm fuːd /', 'Food and Drinks'),
	(343, 'chicken breast', N'ức gà',  N'/ˈtʃɪkɪn brest /', 'Food and Drinks'),
	(344, 'beefsteak', N'bít tết',   N'/ˈbiːfsteɪk/', 'Food and Drinks'),
	(345, '﻿shellfish', N'hải sản có vỏ', N'/ˈʃelfɪʃ/', 'Food and Drinks'),
	(346, 'seafood', N'hải sản',   N'/ˈsiːfuːd/', 'Food and Drinks'),
	(347, 'fish', N'cá',  N'/fɪʃ/', 'Food and Drinks'),
	(348, 'shrimps', N'tôm',  N'/ʃrɪmps/', 'Food and Drinks'),
	(349, 'crab', N'cua', N'/kræb/', 'Food and Drinks'),
	(350, 'octopus', N'bạch tuộc',  N'/ˈɑːktəpəs/', 'Food and Drinks'),
	(351, '﻿squid', N'mực', N'/skwɪd/', 'Food and Drinks'),
	(352, 'snails', N'ốc', N'/sneɪlz/', 'Food and Drinks'),
	(353, 'jam', N'mứt',  N'/dʒæm/', 'Food and Drinks'),
	(354, 'French fries', N'khoai tây chiên kiểu Pháp',   N'/frentʃ fraɪ /', 'Food and Drinks'),
	(355, 'baked potato', N'khoai tây đút lò', N'/beɪk pəˈteɪtoʊ /', 'Food and Drinks'),
	(356, 'hamburger', N'hăm-bơ-gơ',   N'/ˈhæmbɜːrɡər/', 'Food and Drinks'),
	(357, 'sandwich', N'món kẹp',  N'/ˈsænwɪtʃ/', 'Food and Drinks'),
	(358, 'pie', N'bánh có nhân',  N'/paɪ/', 'Food and Drinks'),
	(359, 'gruel', N'chè', N'/ˈɡruːəl/', 'Food and Drinks'),
	(360, 'crepe', N'bánh kếp',  N'/kreɪp/', 'Food and Drinks'),
	(361, 'waffle', N'bánh tổ ong', N'/ˈwɑːfl/', 'Food and Drinks'),
	(362, 'pizza', N'bánh pi-za', N'/ˈpiːtsə/', 'Food and Drinks'),
	(363, 'curry', N'cà ri',  N'/ˈkɜːri/', 'Food and Drinks'),
	(364, 'ice-cream', N'kem',   N'/aɪs kriːm /', 'Food and Drinks'),
	(365, 'tart', N'bánh trứng', N'/tɑːrt/', 'Food and Drinks'),
	(366, 'rare', N'món tái',   N'/rer/', 'Food and Drinks'),
	(367, 'medium', N'món chín vừa',  N'/ˈmiːdiəm/', 'Food and Drinks'),
	(368, 'well done', N'món chín kỹ',  N'/wel dʌn /', 'Food and Drinks'),
	(369, 'starter', N'món khai vị', N'/ˈstɑːrtər/', 'Food and Drinks'),
	(370, 'main course', N'món chính', N'/meɪn kɔːrs /', 'Food and Drinks'),
	(371, 'dessert', N'món tráng miệng', N'/dɪˈzɜːrt/', 'Food and Drinks'),
	(372, 'wine', N'rượu', N'/waɪn/', 'Food and Drinks'),
	(373, 'beer', N'bia',  N'/bɪr/', 'Food and Drinks'),
	(374, 'alcohol', N'đồ có cồn',   N'/ˈælkəhɔːl/', 'Food and Drinks'),
	(375, 'soda', N'nước sô-đa', N'/ˈsoʊdə/', 'Food and Drinks'),
	(376, 'coke', N'nước ngọt',   N'/koʊk/ ', 'Food and Drinks'),
	(377, 'juice', N'nước ép hoa quả',  N'/dʒuːs/', 'Food and Drinks'),
	(378, 'smoothie', N'sinh tố',  N'/ˈsmuːði/', 'Food and Drinks'),
	(379, 'lemonade', N'nước chanh', N'/ˌleməˈneɪd/', 'Food and Drinks'),
	(380, 'coffee', N'cà phê',  N'/ˈkɑːfi/', 'Food and Drinks'),
	(381, 'cocktail', N'rượu cốc-tai', N'/ˈkɑːkteɪl/', 'Food and Drinks'),
	(382, 'tea', N'trà', N'/tiː/', 'Food and Drinks'),
	(383, 'iced tea', N'trà đá',  N'/ aɪst tiː/', 'Food and Drinks'),
	(384, 'milk', N'sữa',   N'/mɪlk/', 'Food and Drinks'),
	(385, 'sugar', N'đường', N'/’ʃugə/', 'Food and Drinks'),
	(386, 'salt', N'muối',   N'/sɔ:lt/', 'Food and Drinks'),
	(387, 'pepper', N'hạt tiêu',  N'/’pepər/', 'Food and Drinks'),
	(388, 'vinegar', N'giấm',  N'/’vinigə/', 'Food and Drinks'),
	(389, 'fish sauce', N'nước mắm', N'/fiʃ sɔ:s/', 'Food and Drinks'),
	(390, 'soy sauce', N'nước tương',  N'/sɔi sɔ:s/', 'Food and Drinks'),
	(391, 'mustard', N'mù tạt', N'/’mʌstəd/', 'Food and Drinks'),
	(392, 'garlic', N'tỏi', N'/’gɑ:lik/', 'Food and Drinks'),
	(393, 'curry powder', N'bột cà ri',  N'/’kʌri ‘paudə/', 'Food and Drinks'),
	(394, 'cooking oil', N'dầu ăn',   N'/’kukiɳ ɔil/', 'Food and Drinks'),
	(395, 'olive oil', N'dầu ô liu', N'/’ɔliv ɔil/', 'Food and Drinks'),
	(396, 'green onion', N'hành lá',   N'/gri:n ‘ʌnjən/', 'Food and Drinks'),
	(397, 'mayonnaise', N'xốt mai-ô-ne',  N'/,meiə’neiz/', 'Food and Drinks'),
	(398, 'ketchup', N'xốt cà chua',  N'/’ketʃəp/', 'Food and Drinks'),
	(399, 'chocolate', N'sô cô la', N'/ˈCHäk(ə)lət/', 'Food and Drinks'),
	(400, 'vera', N'cây nha đam',  N'/vera/', 'Food and Drinks')


INSERT INTO FLASHCARD
	(ID, ENG, VIE, PRONUNCIATION, FIELD)
VALUES
	(401, 'horse race', N'đua ngựa', N'/hɔ:s reis/', 'Sport'),
	(402, 'soccer', N'bóng đá', N'/’sɒkə/', 'Sport'),
	(403, 'basketball', N'bóng rổ',  N'/’bɑ:skitbɔ:l/', 'Sport'),
	(404, 'swimming', N'bơi lội',   N'/’swimiŋ/', 'Sport'),
	(405, 'tennis', N'quần vợt', N'/’tenis/', 'Sport'),
	(406, 'table tennis', N'bóng bàn',   N'/’teibl ’tenis/', 'Sport'),
	(407, 'athletics', N'điền kinh',  N'/æθ’letiks/', 'Sport'),
	(408, 'volleyball', N'bóng chuyền',  N'/’vɔlibɔ:l/', 'Sport'),
	(409, 'badminton', N'cầu lông', N'/’bædmintən/', 'Sport'),
	(410, 'weightlifting', N'cử tạ',  N'/’weit’liftiŋ/', 'Sport'),
	(411, 'archery', N'bắn cung', N'/‘ɑ:tʃəri/', 'Sport'),
	(412, 'gymnastics', N'thể dục dụng cụ',  N'/ʤim’næstiks/', 'Sport'),
	(413, 'fencing', N'đấu kiếm', N'/’fensiŋ/', 'Sport'),
	(414, 'cycling', N'đua xe đạp', N'/’saikliŋ/', 'Sport'),
	(415, 'regatta', N'đua thuyền',  N'/ri’gætə/', 'Sport'),
	(416, 'boxing', N'quyền anh', N'/’bɔksiŋ/', 'Sport'),
	(417, 'rugby', N'bóng bầu dục',  N'/’r˄bi/', 'Sport'),
	(418, 'ưrestle', N'vật',  N'/’resl/', 'Sport'),
	(419, 'golf', N'gôn',  N'/gɔlf/', 'Sport'),
	(420, 'baseball', N'bóng chày',  N'/’beisbɔ:l/', 'Sport'),
	(421, 'ice-skating', N'trượt băng', N'/ais ‘skeitiŋ/', 'Sport'),
	(422, 'water-skiing', N'lướt ván nước', N'/wɔ:tə ‘ski:iŋ/', 'Sport'),
	(423, 'hockey', N'khúc côn cầu',  N'/’hɒki/', 'Sport'),
	(424, 'high jumping', N'nhảy cao',   N'/hai ʤ˄mpiŋ/', 'Sport'),
	(425, 'snooker', N'bi da', N'/’snu:kə/', 'Sport'),
	(426, 'hurdle rate', N'nhảy rào',   N'/’hə:dl reit/', 'Sport'),
	(427, 'scuba diving', N'lặn',  N'/’sku:bə ‘daiviŋ/', 'Sport'),
	(428, 'eurythmics', N'thể dục nhịp điệu',  N'/ju:’riðmiks/', 'Sport'),
	(429, 'windsurfing', N'lướt sóng', N'/’windsɜ:fiŋ/', 'Sport'),
	(430, 'polo', N'đánh bóng trên ngựa',  N'/’poulou/', 'Sport'),
	(431, 'pole vault', N'nhảy sào', N'/’pokl vɔ:lt/', 'Sport'),
	(432, 'marathon race', N'chạy maratông',  N'/’mærəƟən reis/', 'Sport'),
	(433, 'javelin', N'ném lao', '/’ʤævlin/', N'Sport'),
	(434, 'hurdling', N'chạy nhảy qua sào', N'/’hə:dliŋ/', 'Sport'),
	(435, 'rollerblading', N'trượt pa-tanh',  N'/ˈrəʊ.ləˌbleɪ.dɪŋ/', 'Sport'),
	(436, 'jogging', N'chạy bộ', N'/‘dʒɔgiη/', 'Sport'),
	(437, 'judo', N'võ judo',  N'/‘dʒu:dou/', 'Sport'),
	(438, 'karate', N'võ karate',  N'/kə’rɑ:ti/', 'Sport'),
	(439, 'kickboxing', N'võ đối kháng',  N'/ˈkɪk.bɒk.sɪŋ/', 'Sport'),
	(440, 'hunting', N'đi săn',  N'/‘hʌntiη/', 'Sport'),
	(441, 'martial arts', N'võ thuật', N'/ˌmɑː.ʃəl ˈɑːt/', 'Sport'),
	(442, 'motor racing', N'đua ô tô', N'/ˈməʊ.tə ˌreɪ.sɪŋ/', 'Sport'),
	(443, 'mountaineering', N'leo núi',  N'/,maunti’niəriη/', 'Sport'),
	(444, 'shooting', N'bắn súng',   N'/‘∫u:tiη/', 'Sport'),
	(445, 'shooting', N'trượt ván', N'/skeit‘bɔ:diη/', 'Sport'),
	(446, 'skiing', N'trượt tuyết',   N'/‘ski:iη/', 'Sport'),
	(447, 'snooker', N'trượt tuyết',  N'/‘snu:kə/', 'Sport'),
	(448, 'surfing', N'lướt sóng',  N'/‘sɜ:fiη/', 'Sport'),
	(449, 'snowboarding', N'trượt tuyết ván', N'/snou‘bɔ:diη/', 'Sport'),
	(450, 'squash', N'bóng quần',  N'/skwɔ∫/', 'Sport')

INSERT INTO FLASHCARD
	(ID, ENG, VIE, PRONUNCIATION, FIELD)
VALUES
	(501, 'avocado', N'bơ', N'/¸ævə´ka:dou/', 'Fruits'),
	(502, 'apple', N'táo', N'/’æpl/', 'Fruits'),
	(503, 'orange', N'cam',  N'/ɒrɪndʒ/', 'Fruits'),
	(504, 'banana', N'chuối',   N'/bə’nɑ:nə/', 'Fruits'),
	(505, 'grape', N'nho', N'/greɪp/', 'Fruits'),
	(506, 'grapefruit', N'bưởi',   N'/’greipfru:t/', 'Fruits'),
	(507, 'starfruit', N'khế',  N'/’stɑ:r.fru:t/', 'Fruits'),
	(508, 'mango', N'xoài',  N'/´mæηgou/', 'Fruits'),
	(509, 'pineapple', N'dứa, thơm', N'/’pain,æpl/', 'Fruits'),
	(510, 'mangosteen', N'măng cụt',  N'/ˈmaŋgəstiːn/', 'Fruits'),
	(511, 'mandarin', N'quýt', N'/’mændərin/', 'Fruits'),
	(512, 'kiwi fruit', N'kiwi',  N'/’ki:wi:fru:t/', 'Fruits'),
	(513, 'kumquat', N'quất', N'/’kʌmkwɔt/', 'Fruits'),
	(514, 'jackfruit', N'mít', N'/’dʒæk,fru:t/', 'Fruits'),
	(515, 'durian', N'sầu riêng',  N'/´duəriən/', 'Fruits'),
	(516, 'lemon', N'chanh vàng', N'/´lemən/', 'Fruits'),
	(517, 'lime', N'chanh vỏ xanh',  N'/laim/', 'Fruits'),
	(518, 'papaya', N'đu đủ',  N'/pə´paiə/', 'Fruits'),
	(519, 'soursop', N'mãng cầu xiêm',  N'/’sɔ:sɔp/', 'Fruits'),
	(520, 'custard-apple', N'mãng cầu (na)',  N'/’kʌstəd,æpl/', 'Fruits'),
	(521, 'plum', N'mận', N'/plʌm/', 'Fruits'),
	(522, 'apricot', N'mơ', N'/ˈæ.prɪ.kɒt/', 'Fruits'),
	(523, 'peach', N'đào',  N'/pitʃ/ ', 'Fruits'),
	(524, 'cherry', N'anh đào',   N'/´tʃeri/', 'Fruits'),
	(525, 'sapota', N'sapôchê', N'/ˈbiːvər/', 'Fruits'),
	(526, 'rambutan', N'chôm chôm',   N'/ræmˈbuːtən/', 'Fruits'),
	(527, 'coconut', N'dừa',  N'/’koukənʌt/', 'Fruits'),
	(528, 'guava', N'ổi',  N'/´gwa:və/', 'Fruits'),
	(529, 'pear', N'lê', N'/peə/', 'Fruits'),
	(530, 'pig', N'sung',  N'/fig/', 'Fruits'),
	(531, 'dragon fruit', N'thanh long', N'/’drægənfru:t/', 'Fruits'),
	(532, 'melon', N'dưa',  N'/´melən/', 'Fruits'),
	(533, 'watermelon', N'dưa hấu', N'/’wɔ:tə´melən/', 'Fruits'),
	(534, 'lychee', N'vải', N'/’li:tʃi:/', 'Fruits'),
	(535, 'longan', N'nhãn',  N'/lɔɳgən/', 'Fruits'),
	(536, 'pomegranate', N'lựu', N'/´pɔm¸grænit/', 'Fruits'),
	(537, 'berry', N'dâu',  N'/’beri/', 'Fruits'),
	(538, 'strawberry', N'dâu tây',  N'/ˈstrɔ:bəri/', 'Fruits'),
	(539, 'passion-fruit', N'chanh dây',  N'/´pæʃən¸fru:t/', 'Fruits'),
	(540, 'persimmon', N'hồng',  N'/pə´simən/', 'Fruits'),
	(541, 'tamarind', N'me', N'/’tæmərind/', 'Fruits'),
	(542, 'cranberry', N'quả nam việt quất', N'/’krænbəri/', 'Fruits'),
	(543, 'jujube', N'táo ta',  N'/´dʒu:dʒu:b/', 'Fruits'),
	(544, 'dates', N'quả chà là',   N'/deit/', 'Fruits'),
	(545, '﻿green almonds', N'quả hạnh xanh', N'/gri:n ‘ɑ:mənd/', 'Fruits'),
	(546, 'ugli fruit', N'quả chanh vùng Tây Ấn',   N'/’ʌgli’fru:t/', 'Fruits'),
	(547, 'citron', N'quả thanh yên',  N'/´sitrən/', 'Fruits'),
	(548, 'currant', N'nho Hy Lạp',  N'/´kʌrənt/', 'Fruits'),
	(549, 'indian cream cobra melon', N'cóc', N'/’æmbə’rælə/', 'Fruits'),
	(550, 'stingray', N'dưa gang',  N'/´indiən kri:m ‘koubrə ´melən/', 'Fruits'),
	(451, '﻿granadilla', N'dưa Tây', N'/,grænə’dilə/', 'Fruits'),
	(452, 'cantaloupe', N'dưa vàng', N'/’kæntəlu:p/', 'Fruits'),
	(453, 'honeydew', N'dưa xanh',  N'/’hʌnidju:/', 'Fruits'),
	(454, 'malay apple', N'điều',   N'/mə’lei ‘æpl/', 'Fruits'),
	(455, 'star apple', N'vú sữa', N'/’stɑ:r ‘æpl/', 'Fruits'),
	(456, 'almond', N'quả hạnh',   N'/’a:mənd/', 'Fruits'),
	(457, 'chestnut', N'hạt dẻ',  N'/´tʃestnʌt/', 'Fruits'),
	(458, 'honeydew melon', N'dưa bở ruột xanh',  N'/’hʌnidju: ´melən/', 'Fruits'),
	(459, 'blackberries', N'mâm xôi đen', N'/´blækbəri/', 'Fruits'),
	(460, 'raisin', N'nho khô',  N'/’reizn/', 'Fruits'),
	(461, 'broccoli', N'bông cải xanh', N'/ˈbrɒk.əl.i/', 'Fruits'),
	(462, 'artichoke', N'atiso', N'/ˈɑː.tɪ.tʃəʊk/', 'Fruits'),
	(463, 'celery', N'cần tây',  N'/ˈsel.ər.i/', 'Fruits'),
	(464, 'pea', N'đậu Hà Lan',   N'/piː/', 'Fruits'),
	(465, 'fennel', N'thì là', N'/ˈfen.əl/', 'Fruits'),
	(466, 'asparagus', N'măng tây',   N'/əˈspær.ə.ɡəs/', 'Fruits'),
	(467, 'leek', N'tỏi tây',  N'/liːk/', 'Fruits'),
	(468, 'beans', N'đậu',  N'/biːn/', 'Fruits'),
	(469, 'horseradish', N'cải ngựa', N'/ˈhɔːsˌræd.ɪʃ/', 'Fruits'),
	(470, 'corn', N'ngô',  N'/kɔːn/', 'Fruits'),
	(471, 'lettuce', N'rau diếp', N'/ˈlet.ɪs/', 'Fruits'),
	(472, 'beetroot', N'củ dền', N'/ˈbiːt.ruːt/', 'Fruits'),
	(473, 'mushroom', N'nấm',  N'/ˈmʌʃ.ruːm/', 'Fruits'),
	(474, 'squash', N'bí',   N'/skwɒʃ/', 'Fruits'),
	(475, 'cucumber', N'dưa chuột', N'/ˈkjuː.kʌm.bər/', 'Fruits'),
	(476, 'potato', N'khoai tây',   N'/pəˈteɪ.təʊ/', 'Fruits'),
	(477, 'garlic', N'tỏi',  N'/ˈɡɑː.lɪk/', 'Fruist'),
	(478, 'onion', N'hành tây',  N'/ˈʌn.jən/', 'Fruits'),
	(479, 'green onion', N'hành lá', N'/ˌɡriːn ˈʌn.jən/', 'Fruits'),
	(480, 'tomato', N'cà chua',  N'/təˈmɑː.təʊ/', 'Fruits'),
	(481, 'marrow', N'bí xanh', N'/ˈmær.əʊ/', 'Fruits'),
	(482, 'radish', N'củ cải', N'/ˈræd.ɪʃ/', 'Fruits'),
	(483, 'bell pepper', N'ớt chuông',  N'/ˈbel ˌpep.ər/', 'Fruits'),
	(484, 'hot pepper', N'ớt cay',   N'/hɒt, pep.ər/', 'Fruits'),
	(485, 'carrot', N'cà rốt', N'/ˈkær.ət/', 'Fruits'),
	(486, 'pumpkin', N'bí đỏ',   N'/ˈpʌmp.kɪn/', 'Fruits'),
	(487, 'watercress', N'cải xoong',  N'/ˈwɔː.tə.kres/', 'Fruits'),
	(488, 'yam', N'khoai mỡ',  N'/jæm/', 'Fruits'),
	(489, 'sweet potato', N'khoai lang', N'/ˌswiːt pəˈteɪ.təʊ/', 'Fruits'),
	(490, 'cassava root', N'khoai mì',  N'/kəˈsɑː.və, ruːt/', 'Fruits'),
	(491, 'herbs', N'rau thơm', N'/hɜːb/', 'Fruits'),
	(492, 'wintermelon', N'bí đao', N'/ˈwin(t)ər ˈmelən/', 'Fruits'),
	(493, 'ginger', N'gừng',  N'/ˈdʒɪn.dʒər/', 'Fruits'),
	(494, 'lotus root', N'củ sen',   N'/ˈlōdəs ro͞ot/', 'Fruits'),
	(495, 'turmetic', N'nghệ', N'/ˈtərmərik/', 'Fruits'),
	(496, 'kohlrabi', N'su hào',   N'/ˌkəʊlˈrɑː.bi/', 'Fruits'),
	(497, 'knotgrass', N'rau răm',  N'/ˈnätɡras/', 'Fruits'),
	(498, 'mint leaves', N'lá bạc hà',  N'/mint leaves/', 'Fruits'),
	(499, 'coriander', N'rau mùi', N'/ˌkɒr.iˈæn.dər/', 'Fruits'),
	(500, 'water morning glory', N'rau muống',  N'/ˈwôdər ˈmôrniNG ˈɡlôrē/', 'Fruits'),
	(551, 'cyclamen', N'hoa anh thảo', N'/ˈsaɪkləmən/', 'Plants'),
	(552, 'carnation', N'hoa cẩm chướng', N'/kɑːˈneɪʃən/', 'Plants'),
	(553, 'poppy', N'hoa anh túc',  N'/ˈpɒpi/', 'Plants'),
	(554, 'pansy', N'hoa păng-xê',   N'/ˈpænzi/', 'Plants'),
	(555, 'violet', N'hoa vi-ô-lét', N'/ˈvaɪələt/', 'Plants'),
	(556, 'mimosa', N'hoa xấu hổ; hoa trinh nữ',   N'/mɪˈmoʊsə/', 'Plants'),
	(557, 'lily', N'hoa huệ tây; hoa loa kèn',  N'/ˈlɪli/', 'Plants'),
	(558, 'gladiolus', N'hoa lay-ơn',  N'/ɡlædiˈoʊləs/', 'Plants'),
	(559, 'forget-me-not', N'hoa lưu ly', N'/fɚˈɡet.mi.nɑːt/', 'Plants'),
	(560, 'bougainvillea', N'hoa giấy',  N'/ˌbuːɡənˈvɪliə/', 'Plants'),
	(561, 'cactus flower', N'hoa xương rồng', N'/ˈkæktəs ˈflaʊər/', 'Plants'),
	(562, 'camellia', N'hoa trà', N'/kəˈmiːliə /', 'Plants'),
	(563, 'chrysanthemum', N'cúc đại đóa',  N'/krɪˈsænθəməm/', 'Plants'),
	(564, 'cockscomb', N'hoa mào gà',   N'/ˈkɒkskəʊm/', 'Plants'),
	(565, 'daffodil', N'hoa thủy tiên vàng', N'/ˈdæfədɪl/', 'Plants'),
	(566, 'dahlia', N'hoa thược dược', N'/ˈdæliə/', 'Plants'),
	(567, 'flamboyant', N'hoa phượng',  N'/flæmˈbɔɪənt/', 'Plants'),
	(568, 'frangipani', N'hoa sứ',  N'/ˌfrændʒiˈpæni/', 'Plants'),
	(569, 'gerbera', N'hoa đồng tiền', N'/ˈdʒəːb(ə)rə /', 'Plants'),
	(570, 'hibiscus', N'hoa dâm bụt',  N'/hɪˈbɪskəs/', 'Plants'),
	(571, 'jasmine', N'hoa nhài', N'/ˈdʒæzmɪn/', 'Plants'),
	(572, 'lavender', N'hoa oải hương', N'/ˈlævəndər/', 'Plants'),
	(573, 'lotus', N'hoa sen',  N'/ˈloʊtəs/', 'Plants'),
	(574, 'lilac', N'hoa tử đinh hương',   N'/ˈlaɪlək/', 'Plants'),
	(575, 'magnolia', N'hoa mộc lan', N'/mæɡˈnoʊliə/', 'Plants'),
	(576, 'marigold', N'hoa vạn thọ',   N'/ˈmæriɡoʊld/', 'Plants'),
	(577, 'tuberose', N'hoa huệ',  N'/ˈtjuːbərəʊz/', 'Plants'),
	(578, 'apricot blossom', N'hoa mai',  N'/ˈæprɪkɑːt ˈblɑːsəm/', 'Plants'),
	(579, 'cherry blossom', N'hoa đào', N'/ˈtʃeri ˈblɑːsəm/', 'Plants'),
	(580, 'dandelion', N'hoa bồ công anh',  N'/ˈdændɪlaɪən/', 'Plants'),
	(581, 'moss rose', N'hoa mười giờ', N'/mɔːs roʊz/', 'Plants'),
	(582, 'hydrangea', N'cẩm tú cầu', N'/haɪˈdreɪndʒə/', 'Plants'),
	(583, 'wildflowers', N'hoa dại',  N'/’waɪld,flaʊɝr/', 'Plants'),
	(584, 'bluebell', N'hoa chuông xanh', N'/’blu:bel/', 'Plants'),
	(585, 'foxglove', N'hoa mao địa hoàng', N'/’fɔksglʌv/', 'Plants'),
	(586, 'waterlily', N'hoa súng',   N'/’wɔ:təlis]/', 'Plants'),
	(587, 'snowdrop', N'hoa giọt tuyết',  N'/’snoudrɔp/', 'Plants'),
	(588, 'thorn', N'gai',  N'/θɔ:n/', 'Plants'),
	(589, 'stem', N'thân cây hoa', N'/stem/', 'Plants'),
	(590, 'cockroach', N'con gián',  N'/ˈkɒk.rəʊtʃ/', 'Plants'),
	(591, 'stalk', N'cuống hoa', N'/stɔ:k/', 'Plants'),
	(592, 'pollen', N'phấn hoa', N'/’pɔlən/', 'Plants'),
	(593, 'petal', N'cánh hoa',  N'/’petl/', 'Plants'),
	(594, 'leaf', N'lá',   N'/li:f/', 'Plants'),
	(595, 'bud', N'chồi', N'/bʌd/', 'Plants'),
	(596, 'fruit tree', N'cây ăn quả',   N'/fruːt triː/', 'Plants'),
	(597, 'twig', N'cành cây con',  N'/twig/', 'Plants'),
	(598, 'trunk', N'thân cây to',  N'/trʌηk/', 'Plants'),
	(599, 'branch', N'cành cây', N'/brɑ:nt∫/', 'Plants'),
	(600, 'bark', N'vỏ cây',  N'/bɑ:k/', 'Plants'),
	(601, 'alder', N'cây tổng quán sủi', N'/’ɔl:də/', 'Plants'),
	(602, 'ash', N'cây tần bì', N'/æ∫/', 'Plants'),
	(603, 'beech', N'cây sồi',  N'/bi:t∫/', 'Plants'),
	(604, 'birch', N'cây gỗ bu lô',   N'/bə:t∫/', 'Plants'),
	(605, 'cedar', N'cây tuyết tùng', N'/’si:də/', 'Plants'),
	(606, 'elm', N'cây đu',   N'/elm/', 'Plants'),
	(607, 'fir', N'cây linh sam',  N'/fə:/', 'Plants'),
	(608, 'hazel', N'cây phỉ',  N'/’heizl/', 'Plants'),
	(609, 'hawthorn', N'cây táo gai', N'/’hɔ:θɔ:n/', 'Plants'),
	(610, 'holly', N'cây nhựa ruồi',  N'/’hɔli/', 'Plants'),
	(611, 'lime', N'cây đoan', N'/laim/', 'Plants'),
	(612, 'maple', N'cây thích',  N'/’meipl/', 'Plants'),
	(613, 'oak', N'cây sồi', N'/əʊk/', 'Plants'),
	(614, 'plane', N'cây tiêu huyền', N'/plein/', 'Plants'),
	(615, 'pine', N'cây thông',  N'/pain/', 'Plants'),
	(616, 'poplar', N'cây bạch dương', N'/’pɔplə(r)/', 'Plants'),
	(617, 'weeping willow', N'cây liễu rủ',  N'/ˈwiːpɪŋ ˈwɪləʊ/', 'Plants'),
	(618, 'sycamore', N'cây sung dâu',  N'/’sikəmɔ:/', 'Plants'),
	(619, 'willow', N'cây liễu',  N'/’wilou/', 'Plants'),
	(620, 'yew', N'cây thủy tùng',  N'/ʃiːp/', 'Plants'),
	(621, 'apple tree', N'cây táo', N'/ˈæpl triː/', 'Plants'),
	(622, 'cherry tree', N'cây anh đào', N'/ˈʧɛri triː/', 'Plants'),
	(623, 'chestnut tree', N'cây dẻ',  N'/ˈʧɛsnʌt triː/ ', 'Plants'),
	(624, 'coconut tree', N'cây dừa',   N'/ˈkəʊkənʌt triː/', 'Plants'),
	(625, 'fig tree', N'cây sung', N'/fɪg triː/', 'Plants'),
	(626, 'horse chestnut tree', N'cây dẻ ngựa',   N'/hɔːs ˈʧɛsnʌt triː/', 'Plants'),
	(627, 'olive tree', N'cây ô liu',  N'/ˈɒlɪv triː/', 'Plants'),
	(628, 'pear tree', N'cây lê',  N'/peə triː/', 'Plants'),
	(629, 'plum tree', N'cây mận', N'/plʌm triː/', 'Plants'),
	(630, 'bracken', N'cây dương xỉ diều hâu',  N'/’brækən/', 'Plants'),
	(631, 'bush', N'bụi rậm', N'/bu∫/', 'Plants'),
	(632, 'cactus', N'cây xương rồng',  N'/kæktəs/', 'Plants'),
	(633, 'corn', N'cây ngô', N'/kɔ:n/', 'Plants'),
	(634, 'fern', N'cây dương xỉ', N'/fə:n/', 'Plants'),
	(635, 'flower', N'hoa',  N'/’flauə/', 'Plants'),
	(636, 'grass', N'cỏ trồng', N'/grɑ:s/', 'Plants'),
	(637, 'heather', N'cây thạch nam',  N'/’heðə/', 'Plants'),
	(638, 'herb', N'thảo mộc',  N'/hə:b/', 'Plants'),
	(639, 'ivy', N'cây thường xuân',  N'/’aivi/', 'Plants'),
	(640, '﻿moss', N'rêu',  N'/mɔs/', 'Plants'),
	(641, 'mushroom', N'nấm', N'/’mʌ∫rum/', 'Plants'),
	(642, 'nettle', N'cây tầm ma', N'/’netl/', 'Plants'),
	(643, 'shrub', N'cây bụi',  N'/∫rʌb/', 'Plants'),
	(644, 'wheat', N'lúa mì',   N'/wi:t/', 'Plants'),
	(645, '﻿daisy', N'hoa cúc', N'/ˈdeɪzi/', 'Plants'),
	(646, 'rose', N'hoa hồng',   N'/rəʊz/', 'Plants'),
	(647, 'narcissus', N'hoa thuỷ tiên',  N'/nɑːrˈsɪsəs/', 'Plants'),
	(648, 'orchid', N'hoa phong lan',  N'/ˈɔːkɪd/', 'Plants'),
	(649, 'tulip', N'hoa tu-lip', N'/ˈtjuːlɪp/', 'Plants'),
	(650, 'sunflower', N'hoa hướng dương',  N'/ˈsʌnflaʊər/', 'Plants'),
	(651, '﻿actor', N'nam diễn viên', N'/ˈaktər/', 'Job'),
	(652, 'actress', N'nữ diễn viên', N'/ˈaktrəs/', 'Job'),
	(653, 'comedian', N'diễn viên hài',  N'/kəˈmēdēən/', 'Job'),
	(654, 'composer', N'nhà soạn nhạc',   N'/kəmˈpōzər/', 'Job'),
	(655, 'dancer', N'diễn viên múa', N'/ˈdansər/', 'Job'),
	(656, 'film director', N'đạo diễn phim',   N'/film diˈrektər/', 'Job'),
	(657, 'musician', N'nhạc công',  N'/myo͞oˈziSHən/', 'Job'),
	(658, 'accountant', N'kế toán',  N'/əˈkount(ə)nt/', 'Job'),
	(659, 'architect', N'kiến trúc sư', N'/ˈärkəˌtekt/', 'Job'),
	(660, 'artist', N'họa sĩ',  N'/ˈärdəst/', 'Job'),
	(661, 'assembler', N'công nhân lắp ráp', N'/əˈsemblər/', 'Job'),
	(662, 'astronomer', N'nhà thiên văn học', N'/əˈstränəmər/', 'Job'),
	(663, 'author', N'nhà văn',  N'/ˈôTHər/', 'Job'),
	(664, 'babysister', N'người trông trẻ',   N'/ˈbābēˌsidər/', 'Job'),
	(665, 'baker', N'thợ làm bánh mì', N'/ˈbākər/', 'Job'),
	(666, 'barber', N'thợ hớt tóc', N'/ˈfɒl.kən/', 'Job'),
	(667, 'bartender', N'người pha rượu',  N'/ˈbärˌtendər/', 'Job'),
	(668, 'bricklayer', N'thợ hồ',  N'/ˈbrikˌlāər/', 'Job'),
	(669, 'business man', N'nam doanh nhân', N'/ˈbiznəs man/', 'Job'),
	(670, 'business woman', N'nữ doanh nhân',  N'/ˈbiznəs ˈwo͝omən/', 'Job'),
	(671, 'bus driver', N'tài xế xe bus', N'/bəs ˈdrīvər/', 'Job'),
	(672, 'butcher', N'người bán thịt', N'/ˈbo͝oCHər/', 'Job'),
	(673, 'carpenter', N'thợ mộc',  N'/ˈkärpən(t)ər/', 'Job'),
	(674, 'cashier', N'nhân viên thu ngân',   N'/kaˈSHir/', 'Job'),
	(675, 'chef', N'đầu bếp', N'/SHef/', 'Job'),
	(676, 'cleaner', N'người dọn dẹp',   N'/ˈklēnər/', 'Job'),
	(677, 'computer software engineer', N'kĩ sư phần mềm máy tính',  N'/kəmˈpyo͞odər ˈsôf(t)wer ˌenjəˈnir/', 'Job'),
	(678, 'construction worker', N'công nhân xây dựng',  N'/kənˈstrəkSH(ə)n ˈwərkər/', 'Job'),
	(679, 'custodian', N'người quét dọn', N'/kəsˈtōdēən/', 'Job'),
	(680, 'data entry clerk', N'nhân viên nhập liệu',  N'/ˈdadə ˈentrē klərk/', 'Job'),
	(681, 'delivery person', N'nhân viên giao hàng', N'/dəˈliv(ə)rē ˈpərs(ə)n/', 'Job'),
	(682, 'dentist', N'nha sĩ', N'/ˈden(t)əst/', 'Job'),
	(683, 'designer', N'nhà thiết kế',  N'/dəˈzīnər/', 'Job'),
	(684, 'dockworker', N'công nhân bốc xếp ở cảng', N'/ˈdäkˌwərkər/', 'Job'),
	(685, 'doctor', N'bác sĩ', N'/ˈdäktər/', 'Job'),
	(686, 'dustman', N'người thu rác',   N'/ˈdəstman/', 'Job'),
	(687, 'electrician', N'thợ điện',  N'/əˌlekˈtriSHən/', 'Job'),
	(688, 'engineer', N'kĩ sư',  N'/ˌenjəˈnir/', 'Job'),
	(689, 'factory worker', N'công nhân nhà máy', N'/ˈfakt(ə)rē ˈwərkər/', 'Job'),
	(690, 'farmer', N'nông dân',  N'/ˈfärmər/', 'Job'),
	(691, 'fireman', N'lính cứu hỏa', N'/ˈfī(ə)rmən/', 'Job'),
	(692, 'fisherman', N'ngư dân', N'/ˈfiSHərmən/', 'Job'),
	(693, 'fishmonger', N'người bán cá',  N'/ˈfiSHˌməNGɡər/', 'Job'),
	(694, 'flight attendant', N'tiếp viên hàng không',   N'/flīt əˈtendənt/', 'Job'),
	(695, 'florist', N'người trồng hoa', N'/ˈflôrəst/', 'Job'),
	(696, 'foreman', N'quản đốc, đốc công',   N'/ˈfôrmən/', 'Job'),
	(697, 'gardener', N'người làm vườn',  N'/ˈɡärdnər/', 'Job'),
	(698, 'garment worker', N'công nhân may',  N'/ˈɡärmənt ˈwərkər/', 'Job'),
	(699, 'hairdresser', N'thợ uốn tóc', N'/ˈherˌdresər/', 'Job'),
	(700, 'hair Stylist', N'nhà tạo mẫu tóc',  N'/her ˈstīləst/', 'Job'),
	(701, 'attendant', N'hộ lý', N'/əˈtendənt/', 'Job'),
	(702, 'homemaker', N'người giúp việc nhà', N'/hōmˈmärkət/', 'Job'),
	(703, 'housekeeper', N'nhân viên dọn phòng khách sạn',  N'/ˈhousˌkēpər/', 'Job'),
	(704, 'butler', N'quản gia',   N'/ˈbətlər/', 'Job'),
	(705, 'journalist', N'phóng viên', N'/ˈjərn(ə)ləst/', 'Job'),
	(706, 'judge', N'thẩm phán',   N'/jəj/', 'Job'),
	(707, 'lawyer', N'luật sư',  N'/ˈloiər/', 'Job'),
	(708, 'lecturer', N'giảng viên đại học',  N'/ˈlek(t)SHərər/', 'Job'),
	(709, 'librarian', N'thủ thư', N'/ˌlīˈbrerēən/', 'Job'),
	(710, 'lifeguard', N'nhân viên cứu hộ',  N'/ˈlīfˌɡärd/', 'Job'),
	(711, 'machine operator', N'người vận hành máy móc', N'/məˈSHēn ˈäpəˌrādər/', 'Job'),
	(712, 'maid', N'người giúp việc',  N'/mād/', 'Job'),
	(713, 'mail carrier', N'nhân viên đưa thư', N'/mād ˈkerēər/', 'Job'),
	(714, 'manager', N'quản lý', N'/ˈmanijər/', 'Job'),
	(715, 'manicurist', N'thợ làm móng tay',  N'/ˈmanəˌkyo͝orəst/', 'Job'),
	(716, 'mechanic', N'thợ máy, thợ cơ khí', N'/məˈkanik/', 'Job'),
	(717, 'medical assistant', N'phụ tá bác sĩ',  N'/ˈmedək(ə)l əˈsistənt/', 'Job'),
	(718, 'messenger', N'nhân viên chuyển phát văn kiện',  N'/ˈmes(ə)njər/', 'Job'),
	(719, 'miner', N'thợ mỏ',  N'/ˈmīnər/', 'Job'),
	(720, 'model', N'người mẫu',  N'/ˈmädl/', 'Job'),
	(721, 'mover', N'nhân viên dọn nhà', N'/ˈmo͞ovər/', 'Job'),
	(722, 'newsreader', N'phát thanh viên', N'/ˈn(y)o͞ozˌrēdər/', 'Job'),
	(723, 'nurse', N'y tá',  N'/nərs/ ', 'Job'),
	(724, 'ophthalmology', N'chuyên gia nhãn khoa',   N'/ˌäfTHə(l)ˈmäləjē/', 'Job'),
	(725, 'painter', N'thợ sơn', N'/ˈpān(t)ər/', 'Job'),
	(726, 'pharmacist', N'dược sĩ',   N'/ˈfärməsəst/', 'Job'),
	(727, 'photographer', N'thợ chụp ảnh',  N'/fəˈtäɡrəfər/', 'Job'),
	(728, 'pilot', N'phi công',  N'/ˈpīlət/', 'Job'),
	(729, 'plumber', N'thợ sửa ống nước', N'/ˈpləmər/', 'Job'),
	(730, 'politician', N'chính trị gia',  N'/ˌpäləˈtiSHən/', 'Job'),
	(731, 'policeman', N'nam cảnh sát', N'/pəˈlēsmən/', 'Job'),
	(732, 'postal worker', N'nhân viên bưu điện',  N'/ˈpōstəl ˈwərkər/', 'Job'),
	(733, 'mailman', N'người phát thư', N'/ˈmālman/', 'Job'),
	(734, 'real estate agent', N'nhân viên bất động sản', N'/ˈrē(ə)l iˈstāt ˈājənt/', 'Job'),
	(735, 'receptionist', N'nhân viên tiếp tân',  N'/rəˈsepSH(ə)nəst/', 'Job'),
	(736, 'repair person', N'thợ sửa chữa', N'/rəˈper ˈpərs(ə)n/', 'Job'),
	(737, 'saleperson', N'nhân viên bán hàng',  N'/ˈsālzˌpərs(ə)n/', 'Job'),
	(738, 'sanitation worker', N'nhân viên vệ sinh',  N'/ˌsanəˈtāSH(ə)n ˈwərkər/', 'Job'),
	(739, 'scientist', N'nhà khoa học',  N'ˈsīəntəst', 'Job'),
	(740, '﻿secretary', N'thư kí',  N'/ˈsekrəˌterē/', 'Job'),
	(741, 'security guard', N'nhân viên bảo vệ', N'/səˈkyo͝orədē ɡärd/ ', 'Job'),
	(742, 'shop assistant', N'nhân viên bán hàng', N'/SHäp əˈsistənt/', 'Job'),
	(743, 'soldier', N'quân nhân',  N'/ˈsōljər/', 'Job'),
	(744, 'stock clerk', N'thủ kho',   N'/stäk clerk/', 'Job'),
	(745, '﻿supervisor', N'người giám sát', N'/ˈso͞opərˌvīzər/', 'Job'),
	(746, 'teacher', N'giáo viên',   N'/ˈtēCHər/', 'Job'),
	(747, 'traffic warden', N'nhân viên kiểm soát việc đỗ xe',  N'/ˈtrafik ˈwôrdn/', 'Job'),
	(748, 'veterinarin', N'bác sĩ thú y',  N'/veterinarian/', 'Job'),
	(749, 'welder', N'thợ hàn', N'/ˈweldər/', 'Job'),
	(750, 'window cleaner', N'nhân viên vệ sinh cửa kính',  N'/ˈwindō ˈklēnər/', 'Job')

insert into FLASHCARD
(ID, ENG, VIE, PRONUNCIATION, FIELD)
values
	(0,'Cover','','','')
delete from FLASHCARD where id = 0

select * from FLASHCARD
select * from USERs_INFO
select * from USER_FLASHCARD
insert into USER_FLASHCARD
(ID_USER, ID_CARD, ID_COLLECTION, COLLECTION_NAME)
values
	(1,0,0,'HOCED'),
	(1,0,1, N'Đầu buồi'),
	(1,1,1, N'Đầu buồi'),
	(1,2,1, N'Đầu buồi'),
	(1,0,2, N'Đầu đinh'),
	(1,1,2, N'Đầu đinh'),
	(1,2,3, N'Đầu moi')
delete from USER_FLASHCARD where ID_COLLECTION <> 0
select id_card, eng, vie, pronunciation, field from USER_FLASHCARD, flashcard where ID_USER = 1 and id_collection = 0 and USER_FLASHCARD.ID_CARD = FLASHCARD.ID